// Generated by CoffeeScript 1.6.2
var markerPositioner;

$(function() {
  ($("#nav")).onePageNav({
    changeHash: true,
    currentClass: 'active'
  });
  markerPositioner();
  return ($('.title,.subtitle')).each(function() {
    var parWidth, titleWidth;

    parWidth = ($(this)).parent().width();
    titleWidth = ($(this)).width();
    return ($(this)).css('margin', '0 0 0 ' + (((parWidth - titleWidth) / 2) - 10) + 'px');
  });
});

markerPositioner = function() {
  var markerPos, markerWid;

  markerWid = ($('.active')).width();
  markerPos = ($('.active')).position().left + 20;
  ($('.marker')).css('width', markerWid + 'px');
  return ($('.marker')).css('left', markerPos + 'px');
};
