// Generated by CoffeeScript 1.6.2
$(function() {
  var titleObj, titleWidth;

  $("#nav").onePageNav({
    scrollSpeed: 750,
    changeHash: false,
    currentClass: 'active'
  });
  titleObj = $('.title');
  titleWidth = titleObj.width();
  return titleObj.css('margin', '0 ' + (((1000 - titleWidth) / 2) + 10) + 'px ' + '0 ' + (((1000 - titleWidth) / 2) - 10) + 'px');
});
