// Generated by CoffeeScript 1.6.2
$(function() {
  return $(window).resize(function(event) {
    var minWidth;

    minWidth = 1000;
    if ($(window).width() < minWidth) {
      ($('.bgimg')).css('background-size', minWidth + 'px auto');
      return ($('.bgimg')).css('background-position', 'left center');
    } else {
      ($('.bgimg')).css('background-size', '100% auto');
      return ($('.bgimg')).css('background-position', 'center center');
    }
  });
});
