source 'http://rubygems.org'

# gem 'jekyll-haml'
# gem 'jekyll-sass'

gem 'jekyll'
gem 'jekyll_ext'
gem 'maruku'
gem 'haml'
gem 'rake'
gem 'sass'
gem 'coffee-script'
gem 'fssm'
# gem 'watchr'
gem 'rb-fsevent', '~> 0.9'